apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: chillakurulathasree/node-js:latest   # Update with your DockerHub image
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "10m"
